name = "bash"
version = "1.0.0"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64"]

[container]
registry = "registry.example.com"
organization = "example"

[dependencies]
bash = "*"

[metadata]
display_name = "Portable Bash Environment"
description = """
Ships a self-contained GNU bash shell for linux-64 systems. Useful for quick scripting on hosts 
that do not provide a recent bash runtime by default.
"""
release_notes = """
- Initial portable release of the bash environment.
- Includes GNU bash and its runtime dependencies from conda-forge.
"""
success_message = "Bash is ready. Launch it via <prefix>/bin/bash."
featured_packages = ["bash"]
